name: Question
description: Ask a Zig-related question
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome! There are a bunch of great places to ask Zig-related questions.
        Please take a look at
        [The Community Wiki Page](https://github.com/ziglang/zig/wiki/Community) and
        find a comfy place to ask questions. You will find plenty of helpful people in
        these spaces. However, this issue tracker is not for questions. It is for
        more actionable items such as bug reports and enhancements.
  - type: checkboxes
    id: trash
    attributes:
      label: Please do not open a question issue on the bug tracker
      options:
        - label: "I understand, thank you. I will take my question to one of the community spaces instead"
          required: true
